server:
  port: '8085'
spring:
  data:
    mongodb:
      uri: "mongodb+srv://zajecia:Test1234@mmaszkie-m001.jzdnj.mongodb.net/mmaszkie-m001?retryWrites"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG